version: '3.8'

services:
  postgres:
    container_name: db-barbers-blade
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=barbers_blade
      - POSTGRES_USER=barbers_blade
      - POSTGRES_DB=barbers_blade
